// Opcional: requiere Playwright instalado. La suite Node/Python no lo necesita.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const {mkdirSync,writeFileSync}=require('node:fs');
const {resolve}=require('node:path');
const assert=require('node:assert/strict');
const base=process.env.PORTFOLIO_URL||'http://localhost:8080';
const out=resolve(__dirname,'../screenshots');
mkdirSync(out,{recursive:true});
(async()=>{
  const browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  const checks=[];
  const ready=async text=>{await page.getByText(text,{exact:true}).first().waitFor();await page.locator('.loading').waitFor({state:'hidden'});};
  const visit=async(name,readyText)=>{await page.getByRole('link',{name,exact:true}).click();await ready(readyText);};
  const shot=async file=>page.screenshot({path:resolve(out,file),fullPage:true});
  try{
    await page.goto(base);
    await page.getByRole('button',{name:'Entrar al portafolio'}).click();
    await page.locator('.login').waitFor({state:'hidden'});
    await shot('00-vista-general.png');checks.push('Acceso y vista general');
    await visit('DriveDesk','Contactos en el CRM');
    await page.getByLabel('Nombre',{exact:true}).fill('Contacto navegador');
    await page.getByLabel('Correo',{exact:true}).fill('navegador@example.com');
    await page.getByRole('button',{name:'Crear contacto',exact:true}).click();
    let lead=page.locator('.lead').filter({hasText:'Contacto navegador'});
    await lead.waitFor();await lead.getByRole('combobox').selectOption('contacted');
    await page.locator('.lane.contacted .lead').filter({hasText:'Contacto navegador'}).waitFor();
    await page.getByLabel('Contacto',{exact:true}).selectOption({label:'Contacto navegador'});
    await page.getByRole('button',{name:'Agendar cita',exact:true}).click();
    await page.getByRole('cell',{name:'Contacto navegador',exact:true}).waitFor();
    await page.reload();await ready('Contactos en el CRM');
    assert.equal(await page.locator('.lane.contacted .lead').filter({hasText:'Contacto navegador'}).count(),1);
    await shot('01-drivedesk.png');checks.push('CRM: crear, cambiar etapa, agendar y persistir');
    await visit('StockFlow','Unidades disponibles');
    const product=page.locator('.product').filter({hasText:'Mouse inalámbrico'});
    await product.getByRole('spinbutton').fill('2');await product.getByRole('button',{name:'Reservar',exact:true}).click();
    const order=page.getByRole('row').filter({has:page.getByRole('cell',{name:'Mouse inalámbrico',exact:true})});
    await order.getByRole('button',{name:'Confirmar'}).waitFor();await order.getByRole('button',{name:'Confirmar'}).click();
    await order.getByText('Confirmado',{exact:true}).waitFor();
    await shot('02-stockflow.png');checks.push('Stock: reservar y confirmar un pedido');
    await visit('CampaignLab','Inversión publicitaria');
    await page.getByText(/42 registros incluidos/).waitFor();
    await page.getByLabel('Desde',{exact:true}).fill('2027-01-01');await page.getByLabel('Hasta',{exact:true}).fill('2027-01-02');
    await page.getByRole('button',{name:'Filtrar',exact:true}).click();await page.getByText(/0 registros incluidos/).waitFor();
    assert.equal(await page.getByText('NaN',{exact:true}).count(),0);
    await page.getByLabel('Desde',{exact:true}).fill('2026-09-01');await page.getByLabel('Hasta',{exact:true}).fill('2026-09-14');
    await page.getByRole('button',{name:'Filtrar',exact:true}).click();await page.getByText(/42 registros incluidos/).waitFor();
    await shot('03-campaignlab.png');checks.push('Campañas: métricas, gráfico y periodo vacío');
    await visit('EvidenceDesk','Documentos cargados');
    await page.getByRole('button',{name:'Buscar fuentes',exact:true}).click();await page.locator('.sourcecard').first().waitFor();
    assert.match(await page.locator('.sourcecard').first().innerText(),/Guía de entregas/);
    await page.getByLabel('Pregunta para buscar en documentos').fill('fotosíntesis dinosaurios');
    await page.getByRole('button',{name:'Buscar fuentes',exact:true}).click();await page.getByText('No hay evidencia suficiente para esta consulta.',{exact:true}).last().waitFor();
    await page.getByLabel('Título',{exact:true}).fill('Prueba de texto seguro');
    await page.getByLabel('Contenido',{exact:true}).fill('Documento xss de prueba. <img src=x onerror="window.portfolioXss=true"> El contenido se muestra como texto.');
    await page.getByRole('button',{name:'Añadir documento',exact:true}).click();await page.getByText('Prueba de texto seguro',{exact:true}).waitFor();
    await page.getByLabel('Pregunta para buscar en documentos').fill('xss');await page.getByRole('button',{name:'Buscar fuentes',exact:true}).click();await page.locator('.sourcecard').first().waitFor();
    assert.equal(await page.evaluate(()=>window.portfolioXss),undefined);
    assert.equal(await page.locator('.sourcecard img').count(),0);
    await page.getByLabel('Pregunta para buscar en documentos').fill('¿Cuánto tarda la entrega?');await page.getByRole('button',{name:'Buscar fuentes',exact:true}).click();await page.getByText('[1] Guía de entregas',{exact:true}).waitFor();
    await shot('04-evidencedesk.png');checks.push('Búsqueda: fuentes, abstención y contenido HTML seguro');
    await visit('SignalOps','Servicios saludables');
    const service=page.locator('.service').filter({hasText:'API de ventas'});
    for(let i=1;i<=3;i++){await service.getByRole('button',{name:'Simular fallo',exact:true}).click();await service.getByText(new RegExp(`${i} fallos consecutivos`)).waitFor();}
    await page.getByRole('button',{name:'Reconocer',exact:true}).click();await page.getByText('En atención',{exact:true}).waitFor();
    await shot('05-signalops.png');
    for(let i=1;i<=2;i++){await service.getByRole('button',{name:'Enviar OK',exact:true}).click();await service.getByText(new RegExp(`${i} señales saludables consecutivas`)).waitFor();}
    await page.getByText('Resuelto',{exact:true}).waitFor();checks.push('Ops: abrir, reconocer y resolver incidente');
    await page.setViewportSize({width:390,height:844});
    await page.getByRole('link',{name:'Vista general',exact:true}).click();await page.getByRole('heading',{name:'Cinco ideas. Código que funciona.'}).waitFor();
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
    await shot('06-movil.png');checks.push('Diseño móvil sin desbordamiento horizontal');
    await page.getByRole('button',{name:'Salir',exact:true}).click();await page.locator('.login').waitFor();
    await page.getByLabel('Usuario',{exact:true}).fill('lector');await page.getByLabel('Contraseña',{exact:true}).fill('Lectura-2026!');await page.getByRole('button',{name:'Entrar al portafolio'}).click();await page.locator('.login').waitFor({state:'hidden'});
    await visit('StockFlow','Unidades disponibles');assert.equal(await page.getByRole('button',{name:'Reservar',exact:true}).first().isDisabled(),true);checks.push('Permisos de lectura en la interfaz');
    assert.deepEqual(errors,[]);
    const report={passed:checks.length,failed:0,checks,page_errors:errors};writeFileSync(resolve(out,'browser-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
  }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
