import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {store} from '../core/store.ts';
import {DomainError} from '../core/domain.ts';
import {crm} from '../projects/01-drivedesk/domain.ts';
import {inventory} from '../projects/02-stockflow/domain.ts';
import {operations,verifySignature} from '../projects/05-signalops/domain.ts';
const rejects=(fn:()=>unknown,status:number)=>assert.throws(fn,(error)=>error instanceof DomainError&&error.status===status);
function fixture(){const db=store(':memory:',false);let time=1800000000000;const clock=()=>time;return {db,clock,advance:(ms:number)=>time+=ms};}
const input={name:'Contacto de prueba',email:'persona@example.com',source:'Referido',value_cents:35000000};
test('CRM: rechaza saltos de nuevo a ganado y no registra cambios parciales',()=>{const{db,clock}=fixture(),service=crm(db,clock),lead=service.create(input);rejects(()=>service.transition(lead.id,'won',1),409);assert.equal(service.list().leads[0].stage,'new');assert.equal(service.list().audit.length,1);db.close();});
test('CRM: detecta una revisión desactualizada',()=>{const{db,clock}=fixture(),service=crm(db,clock),lead=service.create(input);service.transition(lead.id,'contacted',1);rejects(()=>service.transition(lead.id,'lost',1),409);assert.equal(service.list().leads[0].stage,'contacted');db.close();});
test('CRM: ganado es terminal; perdido permite reabrir',()=>{const{db,clock}=fixture(),service=crm(db,clock),lead=service.create(input);service.transition(lead.id,'contacted',1);service.transition(lead.id,'meeting',2);service.transition(lead.id,'won',3);rejects(()=>service.transition(lead.id,'new',4),409);const lost=service.create({...input,email:'otro@example.com'});service.transition(lost.id,'lost',1);assert.equal(service.transition(lost.id,'new',2).stage,'new');db.close();});
test('CRM: valida correo, valores enteros y fechas futuras',()=>{const{db,clock}=fixture(),service=crm(db,clock);rejects(()=>service.create({...input,email:'incorrecto'}),400);rejects(()=>service.create({...input,value_cents:1.5}),400);const lead=service.create(input);rejects(()=>service.appointment(lead.id,new Date(clock()-1).toISOString(),'Visita'),400);db.close();});
test('CRM: no permite dos citas en el mismo horario',()=>{const{db,clock}=fixture(),service=crm(db,clock),lead=service.create(input),other=service.create({...input,email:'otra@example.com'}),time=new Date(clock()+3600000).toISOString();service.appointment(lead.id,time,'Visita');rejects(()=>service.appointment(other.id,time,'Visita'),409);assert.equal(service.list().appointments.length,1);db.close();});
test('CRM: una búsqueda con sintaxis SQL no modifica la base',()=>{const{db,clock}=fixture(),service=crm(db,clock);service.create(input);assert.equal(service.list("'; DROP TABLE leads; --").leads.length,0);assert.equal(service.list().leads.length,1);db.close();});
function stockFixture(){const f=fixture();f.db.prepare('INSERT INTO products(id,name,category,price_cents,stock) VALUES(?,?,?,?,?)').run('p','Producto','Demo',19900,3);return {...f,service:inventory(f.db,f.clock)};}
test('Stock: rechaza sobreventa y cantidades inválidas sin efectos parciales',()=>{const{db,service}=stockFixture();rejects(()=>service.reserve('p',4,'k'),409);rejects(()=>service.reserve('p',0,'k'),400);assert.equal(service.list().products[0].available,3);assert.equal(service.list().ledger.length,0);db.close();});
test('Stock: la clave repetida devuelve el mismo pedido y una sola reserva',()=>{const{db,service}=stockFixture(),a=service.reserve('p',2,'k'),b=service.reserve('p',2,'k');assert.equal(a.id,b.id);assert.equal(b.replayed,true);assert.equal(service.list().products[0].reserved,2);assert.equal(service.list().ledger.length,1);db.close();});
test('Stock: la misma clave con otro contenido se rechaza',()=>{const{db,service}=stockFixture();service.reserve('p',1,'k');rejects(()=>service.reserve('p',2,'k'),409);assert.equal(service.list().products[0].reserved,1);db.close();});
test('Stock: confirmar dos veces descuenta una sola vez',()=>{const{db,service}=stockFixture(),order=service.reserve('p',2,'k');service.change(order.id,'confirm');service.change(order.id,'confirm');const state=service.list();assert.equal(state.products[0].stock,1);assert.equal(state.products[0].reserved,0);assert.equal(state.ledger.length,2);assert.equal(state.orders[0].total_cents,39800);db.close();});
test('Stock: cancelar libera la reserva y preserva el stock',()=>{const{db,service}=stockFixture(),order=service.reserve('p',3,'k');service.change(order.id,'cancel');service.change(order.id,'cancel');assert.equal(service.list().products[0].available,3);rejects(()=>service.change(order.id,'confirm'),409);db.close();});
test('Stock: una reserva vencida libera inventario antes de reservar otra',()=>{const{db,service,advance}=stockFixture();const old=service.reserve('p',3,'old');advance(900001);const replacement=service.reserve('p',3,'new');assert.equal(service.list().orders.find(o=>o.id===old.id)?.state,'expired');assert.equal(replacement.state,'reserved');assert.equal(service.list().products[0].reserved,3);rejects(()=>service.change(old.id,'confirm'),409);db.close();});
function opsFixture(){const f=fixture();f.db.prepare('INSERT INTO services(id,name) VALUES(?,?)').run('api','API');let seq=0;const service=operations(f.db,f.clock);const signal=(healthy:boolean)=>{f.advance(1);return service.signal({id:`e${++seq}`,service_id:'api',healthy,created_at:f.clock()});};return {...f,service,signal};}
test('Ops: abre un único incidente al tercer fallo',()=>{const{db,service,signal}=opsFixture();signal(false);signal(false);assert.equal(service.list().incidents.length,0);signal(false);signal(false);assert.equal(service.list().incidents.length,1);assert.equal(service.list().services[0].status,'down');db.close();});
test('Ops: eventos repetidos no incrementan los contadores',()=>{const{db,service,clock}=opsFixture(),event={id:'same',service_id:'api',healthy:false,created_at:clock()};service.signal(event);assert.equal(service.signal(event).replayed,true);assert.equal(service.list().services[0].failure_streak,1);rejects(()=>service.signal({...event,healthy:true}),409);db.close();});
test('Ops: ignora eventos fuera de orden',()=>{const{db,service,signal,clock}=opsFixture();signal(false);const event=service.signal({id:'late',service_id:'api',healthy:true,created_at:clock()-1});assert.equal(event.ignored,true);assert.equal(service.list().services[0].failure_streak,1);db.close();});
test('Ops: reconocer y recibir dos OK resuelve el incidente',()=>{const{db,service,signal}=opsFixture();signal(false);signal(false);signal(false);const id=service.list().incidents[0].id as string;service.acknowledge(id);signal(true);assert.equal(service.list().services[0].status,'recovering');signal(true);assert.equal(service.list().incidents[0].state,'resolved');assert.equal(service.list().audit.length,3);rejects(()=>service.acknowledge(id),409);db.close();});
test('Ops: valida booleanos y ventana temporal del evento',()=>{const{db,service,clock}=opsFixture();rejects(()=>service.signal({id:'a',service_id:'api',healthy:'yes',created_at:clock()}),400);rejects(()=>service.signal({id:'a',service_id:'api',healthy:true,created_at:clock()-300001}),400);db.close();});
test('Webhook: acepta firma válida y rechaza contenido alterado, firma inválida y fecha vieja',()=>{const raw=Buffer.from('{"healthy":true}'),now=1800000000000,time=String(now),secret='test-secret',sig=createHmac('sha256',secret).update(`${time}.`).update(raw).digest('hex');verifySignature(raw,sig,time,secret,now);rejects(()=>verifySignature(Buffer.from('{}'),sig,time,secret,now),401);rejects(()=>verifySignature(raw,'0',time,secret,now),401);rejects(()=>verifySignature(raw,sig,time,secret,now+300001),401);});
