import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createApp} from '../server.ts';
const dir=mkdtempSync(join(tmpdir(),'portfolio-http-')),app=createApp({databasePath:join(dir,'test.sqlite'),quiet:true});
let origin='',cookie='',viewer='';
async function request(path:string,method='GET',payload?:unknown,session=cookie,extra:Record<string,string>={}){return fetch(origin+path,{method,headers:{...(session?{cookie:session}:{}),...(payload!==undefined?{'Content-Type':'application/json'}:{}),...extra},body:payload===undefined?undefined:JSON.stringify(payload)});}
before(async()=>{await new Promise<void>(resolve=>app.server.listen(0,'127.0.0.1',resolve));const addr=app.server.address() as any;origin=`http://127.0.0.1:${addr.port}`;const login=await request('/api/auth/login','POST',{username:'demo',password:'Demo-2026!'},'');cookie=login.headers.get('set-cookie')!.split(';')[0];const read=await request('/api/auth/login','POST',{username:'lector',password:'Lectura-2026!'},'');viewer=read.headers.get('set-cookie')!.split(';')[0];});
after(async()=>{await new Promise<void>(resolve=>app.server.close(()=>resolve()));rmSync(dir,{recursive:true,force:true});});
test('HTTP: requiere sesión y utiliza cookies HttpOnly',async()=>{assert.equal((await request('/api/crm','GET',undefined,'')).status,401);const login=await request('/api/auth/login','POST',{username:'demo',password:'Demo-2026!'},'');assert.match(login.headers.get('set-cookie')!,/HttpOnly; SameSite=Strict/);assert.equal((await request('/api/me')).status,200);});
test('HTTP: un lector consulta datos pero no puede reservar ni crear contactos',async()=>{assert.equal((await request('/api/stock','GET',undefined,viewer)).status,200);assert.equal((await request('/api/stock/reserve','POST',{product_id:'p1',quantity:1,request_key:'denied'},viewer)).status,403);assert.equal((await request('/api/crm/leads','POST',{},viewer)).status,403);assert.equal((await request('/api/evidence/search','POST',{query:'entrega'},viewer)).status,200);});
test('HTTP: rechaza un origen ajeno',async()=>{assert.equal((await request('/api/crm','GET',undefined,cookie,{Origin:'https://attacker.example'})).status,403);});
test('HTTP: errores de JSON y contenido devuelven mensajes controlados',async()=>{const bad=await fetch(origin+'/api/crm/leads',{method:'POST',headers:{cookie,'Content-Type':'application/json'},body:'{'});assert.equal(bad.status,400);assert.equal((await request('/api/crm/leads','POST',{},cookie,{'Content-Type':'text/plain'})).status,415);assert.equal((await request('/api/evidence/import','POST',{title:'Grande',content:'a'.repeat(270000)})).status,413);});
test('HTTP: solicitudes simultáneas no venden más unidades que las disponibles',async()=>{const results=await Promise.all(Array.from({length:10},(_,i)=>request('/api/stock/reserve','POST',{product_id:'p6',quantity:3,request_key:`parallel-${i}`})));assert.equal(results.filter(r=>r.status===201).length,1);assert.equal(results.filter(r=>r.status===409).length,9);const state=await(await request('/api/stock')).json();assert.equal(state.products.find(p=>p.id==='p6').available,0);});
test('HTTP: filtros inválidos del motor Python no se convierten en errores 500',async()=>{assert.equal((await request('/api/campaigns?start=2026-09-20&end=2026-09-01')).status,400);const good=await request('/api/campaigns?start=2026-09-01&end=2026-09-14');assert.equal(good.status,200);assert.equal((await good.json()).records,42);});
test('HTTP: logout invalida la sesión en el servidor',async()=>{const login=await request('/api/auth/login','POST',{username:'demo',password:'Demo-2026!'},''),token=login.headers.get('set-cookie')!.split(';')[0];assert.equal((await request('/api/auth/logout','POST',{},token)).status,200);assert.equal((await request('/api/me','GET',undefined,token)).status,401);});
